ci: don't allow `test!` labels on PRs
It doesn't make sense to allow `test!` labels on PRs, as changes that are limited to `tests` are by definition non-breaking changes.

This adds a check to our `triage` title check workflow and provides instructions for how to correct the problem.

diff --git a/.github/workflows/triage.yml b/.github/workflows/triage.yml
--- a/.github/workflows/triage.yml
+++ b/.github/workflows/triage.yml
@@ -21,3 +21,14 @@ jobs:
             echo "See https://thousandbrainsproject.readme.io/docs/triage#title-1"
             exit 1
           fi
+          
+          pattern="^test!:.+"
+          if [[ ! "${{ github.event.pull_request.title }}" =~ $pattern ]]; then
+            echo "This PR title indicates it is only changing tests, and"
+            echo "that those changes are breaking changes. Changes that"
+            echo "only change files in `tests` cannot produce breaking"
+            echo "changes."
+            echo "  If this PR has non-test changes, then `test` is not the"
+            echo "correct label for this PR."
+            exit 1
+          fi
